spring.application.name=ecommerce
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=shyamsundhar
spring.datasource.password=shyamsundhar@07
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver